    "MORE SLEZ UBEITE            ",
    "A GDE MAMA                  ",
    "UMER NE RODIVSHIS           ",
    "ODNA PULA I UEBKA NET       ",
    "ZXC ZXC ZXC ZXC ZXC         ",
    "f9 ))))                     ",
    "KAKOI ZE TI NULEVII         ",
    "LIVNI IS IGRI PLZ           ",
    "U TEBA PHOTKA GOVNO         ",
    "PIANOE UEBISHE              ",
    "VESHAISA                    ",
    "TI BEZDAR                   ",
    "U TEBA NET BUDUSHEGO        ",
    "U TEBA NICHEGO NE POLUCHITSA",
    "KAK ZE TI SLAB              ",
    "TI NE DOSTOIN ZIZNI         ",
    "POMOISA TI POMOIKA          ",
    "HAHAHHAHAHHAH UBLUDOK       ",
    "ZADUSHI SAM SEBA            ",
    "U TEBA DAZE KROV USHERBNAIA "